version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Clone Docker CLI repository
          command: git clone -b netbsd/v19.03.1 --depth 1 https://github.com/iquiw/cli.git
          working_directory: /go/src/github.com/docker

      - run:
          name: Build Docker CLI
          command: sh build.sh

      - run:
          name: Deploy artifacts to GitHub
          command: sh deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
