version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Clone Docker CLI repository
          command: git clone -b netbsd/v19.03.2 --depth 1 https://github.com/iquiw/cli.git
          working_directory: /go/src/github.com/docker

      - run:
          name: Build Docker CLI
          command: sh build.sh
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - docker-*

  deploy:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/artifacts
      - deploy:
          name: Deploy artifacts to GitHub
          command: sh deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
