version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Clone Docker CLI repository
          command: git clone -b netbsd/18.09 --depth 1 https://github.com/iquiw/cli.git
          working_directory: /go/src/github.com/docker

      - run:
          name: Build Docker CLI
          command: sh build.sh

      - store_artifacts:
          path: /go/src/github.com/docker/cli/cmd/docker/docker-netbsd-amd64.xz
      - store_artifacts:
          path: /go/src/github.com/docker/cli/cmd/docker/docker-netbsd-386.xz

workflows:
  version: 2
  build:
    jobs:
      - build
